-- Run this migration in Supabase SQL Editor for existing projects.

create table if not exists public.event_bookings (
  id bigint generated by default as identity primary key,
  restaurant_slug text not null,
  customer_id uuid references auth.users(id) on delete set null,
  customer_name text not null,
  customer_email text not null,
  event_type text not null,
  event_date date not null,
  guest_count integer not null check (guest_count between 8 and 28),
  requirements text not null,
  quote_amount numeric(10, 2),
  quote_note text,
  status text not null default 'enquiry_sent' check (status in ('enquiry_sent', 'quoted', 'accepted', 'declined_by_customer', 'rejected_by_restaurant', 'expired')),
  reject_reason text,
  created_at timestamptz not null default now()
);

alter table public.event_bookings add column if not exists customer_id uuid references auth.users(id) on delete set null;

drop function if exists public.check_event_availability(text, date, time);
alter table public.event_bookings drop column if exists event_time;
alter table public.event_bookings drop column if exists event_duration;

create index if not exists event_bookings_restaurant_idx on public.event_bookings (restaurant_slug, status);
create index if not exists event_bookings_date_idx on public.event_bookings (event_date);

alter table public.event_bookings enable row level security;

drop policy if exists "Anyone can submit event enquiries" on public.event_bookings;
create policy "Anyone can submit event enquiries"
  on public.event_bookings for insert
  to anon, authenticated
  with check (status = 'enquiry_sent' and (customer_id is null or customer_id = auth.uid()));

drop policy if exists "Customers can read own event enquiries" on public.event_bookings;
create policy "Customers can read own event enquiries"
  on public.event_bookings for select
  to authenticated
  using (customer_id = auth.uid());
grant select on public.event_bookings to authenticated;

drop policy if exists "Admins can read event enquiries" on public.event_bookings;
create policy "Admins can read event enquiries"
  on public.event_bookings for select
  to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()));

drop policy if exists "Admins can update event enquiries" on public.event_bookings;
create policy "Admins can update event enquiries"
  on public.event_bookings for update
  to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()))
  with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

notify pgrst, 'reload schema';
