-- Run this SQL in Supabase SQL Editor.

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  price numeric(10, 2) not null check (price >= 0),
  category text not null,
  image_url text not null,
  service_note text not null default 'Serves 1 / 20 min',
  is_available boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  customer_phone text,
  customer_id uuid references auth.users(id) on delete set null,
  restaurant_slug text not null default 'samundri-food-house',
  table_number integer not null check (table_number between 1 and 5),
  reservation_date date not null,
  guests integer not null check (guests between 1 and 20),
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'cancelled')),
  created_at timestamptz not null default now()
);

create index if not exists reservations_table_date_idx on public.reservations (restaurant_slug, table_number, reservation_date, status);

drop function if exists public.is_table_available(text, integer, date);

create or replace function public.create_reservation(
  p_name text,
  p_email text,
  p_customer_phone text,
  p_restaurant_slug text,
  p_table_number integer,
  p_reservation_date date,
  p_guests integer
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  new_reservation_id bigint;
begin
  if coalesce(btrim(p_name), '') = '' or coalesce(btrim(p_email), '') = '' then
    raise exception 'Name and email are required';
  end if;
  if p_customer_phone is null or p_customer_phone !~ '^\+?[0-9\s()\-]{7,20}$' then
    raise exception 'A valid contact number is required';
  end if;
  if p_restaurant_slug is null or btrim(p_restaurant_slug) = '' then
    raise exception 'A restaurant is required';
  end if;
  if p_table_number not between 1 and 5 or p_guests not between 1 and 20 then
    raise exception 'Invalid table or guest count';
  end if;
  if p_reservation_date is null or p_reservation_date < current_date then
    raise exception 'Choose a current or future reservation date';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      p_restaurant_slug || ':' || p_table_number::text || ':' || p_reservation_date::text,
      0
    )
  );

  if exists (
    select 1
    from public.reservations
    where restaurant_slug = p_restaurant_slug
      and table_number = p_table_number
      and reservation_date = p_reservation_date
      and status in ('pending', 'confirmed')
  ) then
    return null;
  end if;

  insert into public.reservations (name, email, customer_phone, customer_id, restaurant_slug, table_number, reservation_date, guests, status)
  values (btrim(p_name), btrim(p_email), btrim(p_customer_phone), auth.uid(), p_restaurant_slug, p_table_number, p_reservation_date, p_guests, 'confirmed')
  returning id into new_reservation_id;

  return new_reservation_id;
end;
$$;

revoke all on function public.create_reservation(text, text, text, text, integer, date, integer) from public;
grant execute on function public.create_reservation(text, text, text, text, integer, date, integer) to anon, authenticated;

create table if not exists public.event_bookings (
  id bigint generated by default as identity primary key,
  restaurant_slug text not null,
  customer_id uuid references auth.users(id) on delete set null,
  customer_name text not null,
  customer_email text not null,
  event_type text not null,
  event_date date not null,
  guest_count integer not null check (guest_count between 8 and 28),
  requirements text not null,
  quote_amount numeric(10, 2),
  quote_note text,
  status text not null default 'enquiry_sent' check (status in ('enquiry_sent', 'quoted', 'accepted', 'declined_by_customer', 'rejected_by_restaurant', 'expired')),
  reject_reason text,
  created_at timestamptz not null default now()
);

create index if not exists event_bookings_restaurant_idx on public.event_bookings (restaurant_slug, status);
create index if not exists event_bookings_date_idx on public.event_bookings (event_date);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_id uuid references auth.users(id) on delete set null,
  customer_name text not null,
  customer_email text not null,
  customer_phone text,
  total numeric(10, 2) not null check (total >= 0),
  restaurant_slug text not null default 'samundri-food-house',
  order_type text not null default 'preorder' check (order_type in ('preorder', 'delivery')),
  scheduled_at timestamptz,
  delivery_address text,
  payment_method text not null default 'cash' check (payment_method in ('cash', 'bank', 'online')),
  payment_reference text,
  payment_status text not null default 'pending' check (payment_status in ('pending', 'verification_pending', 'paid', 'unavailable')),
  status text not null default 'pending' check (status in ('pending', 'accepted', 'preparing', 'ready', 'completed', 'cancelled')),
  created_at timestamptz not null default now()
);

create index if not exists orders_restaurant_status_idx on public.orders (restaurant_slug, status);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  menu_item_id bigint references public.menu_items(id) on delete set null,
  item_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(10, 2) not null check (unit_price >= 0)
);

alter table public.menu_items enable row level security;
alter table public.reservations enable row level security;
alter table public.event_bookings enable row level security;

drop policy if exists "Public can read available menu items" on public.menu_items;
create policy "Public can read available menu items"
  on public.menu_items for select
  to anon, authenticated
  using (is_available = true);

drop policy if exists "Anyone can request a reservation" on public.reservations;
revoke insert on public.reservations from anon, authenticated;
drop policy if exists "Customers can read their own reservations" on public.reservations;
create policy "Customers can read their own reservations"
  on public.reservations for select
  to authenticated
  using (customer_id = auth.uid());
drop policy if exists "Customers can cancel their own reservations" on public.reservations;
create policy "Customers can cancel their own reservations"
  on public.reservations for update
  to authenticated
  using (customer_id = auth.uid() and status in ('pending', 'confirmed'))
  with check (customer_id = auth.uid() and status = 'cancelled');
grant select, update(status) on public.reservations to authenticated;

drop policy if exists "Anyone can submit event enquiries" on public.event_bookings;
create policy "Anyone can submit event enquiries"
  on public.event_bookings for insert
  to anon, authenticated
  with check (status = 'enquiry_sent' and (customer_id is null or customer_id = auth.uid()));

drop policy if exists "Customers can read own event enquiries" on public.event_bookings;
create policy "Customers can read own event enquiries"
  on public.event_bookings for select
  to authenticated
  using (customer_id = auth.uid());
grant select on public.event_bookings to authenticated;

drop policy if exists "Admins can read event enquiries" on public.event_bookings;
create policy "Admins can read event enquiries"
  on public.event_bookings for select
  to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()));

drop policy if exists "Admins can update event enquiries" on public.event_bookings;
create policy "Admins can update event enquiries"
  on public.event_bookings for update
  to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()))
  with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

alter table public.admin_users enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Customers can create orders" on public.orders;
drop policy if exists "Guests can create orders" on public.orders;
drop policy if exists "Customers can create their own orders" on public.orders;
revoke insert on public.orders from anon, authenticated;

drop policy if exists "Customers can create order items" on public.order_items;
drop policy if exists "Customers can create items for their own orders" on public.order_items;
revoke insert on public.order_items from anon, authenticated;

drop policy if exists "Admins can read orders" on public.orders;
create policy "Admins can read orders"
  on public.orders for select
  to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()));

drop policy if exists "Admins can update orders" on public.orders;
create policy "Admins can update orders"
  on public.orders for update
  to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()))
  with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

drop policy if exists "Admins can read order items" on public.order_items;
create policy "Admins can read order items"
  on public.order_items for select
  to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()));

drop function if exists public.create_order(text, text, numeric, jsonb);
drop function if exists public.create_order(text, text, numeric, jsonb, text, text, timestamptz, text, text, text);

create or replace function public.create_order(
  customer_name text,
  customer_email text,
  order_total numeric,
  items jsonb,
  order_restaurant_slug text default 'samundri-food-house',
  order_type_value text default 'preorder',
  scheduled_at_value timestamptz default null,
  delivery_address_value text default null,
  payment_method_value text default 'cash',
  payment_reference_value text default null,
  customer_phone_value text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_order_id bigint;
  item jsonb;
  found_item_id bigint;
  trusted_price numeric;
  item_quantity integer;
  calculated_total numeric := 0;
  calculated_payment_status text := case when payment_method_value = 'bank' then 'verification_pending' when payment_method_value = 'online' then 'unavailable' else 'pending' end;
begin
  if jsonb_typeof(items) <> 'array' or jsonb_array_length(items) = 0 then
    raise exception 'Order must contain at least one item';
  end if;

  for item in select value from jsonb_array_elements(items) loop
    item_quantity := greatest(1, coalesce((item->>'quantity')::integer, 1));
    select menu.id, menu.price into found_item_id, trusted_price
    from public.menu_items as menu
    where menu.is_available = true
      and (menu.id = nullif(item->>'menu_item_id', '')::bigint or menu.name = item->>'item_name')
    order by (menu.id = nullif(item->>'menu_item_id', '')::bigint) desc
    limit 1;
    if found_item_id is null then
      raise exception 'Menu item is unavailable: %', item->>'item_name';
    end if;
    calculated_total := calculated_total + (trusted_price * item_quantity);
  end loop;

  insert into public.orders (customer_id, customer_name, customer_email, customer_phone, total, status, restaurant_slug, order_type, scheduled_at, delivery_address, payment_method, payment_reference, payment_status)
  values (auth.uid(), customer_name, customer_email, customer_phone_value, calculated_total, 'pending', order_restaurant_slug, order_type_value, scheduled_at_value, delivery_address_value, payment_method_value, payment_reference_value, calculated_payment_status)
  returning id into new_order_id;

  for item in select value from jsonb_array_elements(items) loop
    item_quantity := greatest(1, coalesce((item->>'quantity')::integer, 1));
    select menu.id, menu.price into found_item_id, trusted_price
    from public.menu_items as menu
    where menu.is_available = true
      and (menu.id = nullif(item->>'menu_item_id', '')::bigint or menu.name = item->>'item_name')
    order by (menu.id = nullif(item->>'menu_item_id', '')::bigint) desc
    limit 1;
    insert into public.order_items (order_id, menu_item_id, item_name, quantity, unit_price)
    values (new_order_id, found_item_id, item->>'item_name', item_quantity, trusted_price);
  end loop;

  return new_order_id;
end;
$$;

revoke all on function public.create_order(text, text, numeric, jsonb, text, text, timestamptz, text, text, text, text) from public;
grant execute on function public.create_order(text, text, numeric, jsonb, text, text, timestamptz, text, text, text, text) to anon, authenticated;

drop policy if exists "Admins can read their own allowlist row" on public.admin_users;
create policy "Admins can read their own allowlist row"
  on public.admin_users for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "Admins can read reservations" on public.reservations;
create policy "Admins can read reservations"
  on public.reservations for select
  to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()));

drop policy if exists "Admins can update reservations" on public.reservations;
create policy "Admins can update reservations"
  on public.reservations for update
  to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()))
  with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

drop policy if exists "Admins can delete reservations" on public.reservations;
create policy "Admins can delete reservations"
  on public.reservations for delete
  to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()));

insert into public.menu_items (name, description, price, category, image_url, service_note)
values
  ('East Coast oysters', 'Mignonette, lemon, fresh horseradish', 18, 'Small plates', 'https://images.unsplash.com/photo-1544943910-4c1dc44aab44?auto=format&fit=crop&w=900&q=85', 'To share / 10 min'),
  ('Crab toast', 'Sourdough, cultured butter, pickled fennel', 16, 'Small plates', 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=900&q=85', 'To share / 10 min'),
  ('Grilled whole branzino', 'Salsa verde, charred lemon, sea salt', 29, 'Mains', 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=900&q=85', 'Serves 1 / 20 min'),
  ('Maine lobster roll', 'Brioche, celery, tarragon, drawn butter', 27, 'Mains', 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=900&q=85', 'Serves 1 / 20 min'),
  ('Lemon olive oil cake', 'Citrus curd, mascarpone, almond crumb', 10, 'Sweet things', 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?auto=format&fit=crop&w=900&q=85', 'Sweet course / 10 min'),
  ('Sea salt panna cotta', 'Vanilla, strawberry, toasted oat crumble', 11, 'Sweet things', 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=900&q=85', 'Sweet course / 10 min');
